version: '3'
services:
  text:
    build:
      context: .
      args:
        config_path: config/$ENV
        base_image: jupyter/pyspark-notebook
    user: root
    image: infra/$SERVICE
    working_dir: /opt/infra/$SERVICE
    env_file:
      - config/$ENV/.env
    volumes:
      - .:/opt/infra/ink
      - ./config/$ENV:/home/jovyan/infra
      - ./datalake:/datalake
      - ./datalake/scikit_learn_data:/home/jovyan/scikit_learn_data
    entrypoint: ./config/$ENV/actions/run.sh
